// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfu7oVjuRlw6i7nD_d1sugFzVhn3xXxHo',
    appId: '1:374516738206:web:be7cdf7b6c971e6ff7f38f',
    messagingSenderId: '374516738206',
    projectId: 'cyberchat-da7ef',
    authDomain: 'cyberchat-da7ef.firebaseapp.com',
    storageBucket: 'cyberchat-da7ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3lvKemBBmFA2HSt3PXmvbLZEgZh4cW0U',
    appId: '1:374516738206:android:269ecf9f11b1381ff7f38f',
    messagingSenderId: '374516738206',
    projectId: 'cyberchat-da7ef',
    storageBucket: 'cyberchat-da7ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqub6QfQBagV4egNX4Zn-Yl8NoRaWIRWQ',
    appId: '1:374516738206:ios:090227c541493d7ff7f38f',
    messagingSenderId: '374516738206',
    projectId: 'cyberchat-da7ef',
    storageBucket: 'cyberchat-da7ef.appspot.com',
    iosBundleId: 'com.example.cyberchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqub6QfQBagV4egNX4Zn-Yl8NoRaWIRWQ',
    appId: '1:374516738206:ios:090227c541493d7ff7f38f',
    messagingSenderId: '374516738206',
    projectId: 'cyberchat-da7ef',
    storageBucket: 'cyberchat-da7ef.appspot.com',
    iosBundleId: 'com.example.cyberchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfu7oVjuRlw6i7nD_d1sugFzVhn3xXxHo',
    appId: '1:374516738206:web:16314600e057aac1f7f38f',
    messagingSenderId: '374516738206',
    projectId: 'cyberchat-da7ef',
    authDomain: 'cyberchat-da7ef.firebaseapp.com',
    storageBucket: 'cyberchat-da7ef.appspot.com',
  );
}
